version: "3"

services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile

  nginx:
    image: nginx:1.15
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
      - 9090:9090
    # network_mode: host
